{{- if .Values.storage.enable }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "syslog-ng.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }} 
  storageClassName: {{ .Values.storage.storageClass }} 
{{- end }}
